[1] "Last run started at:"
[1] "2022-01-04 01:30:06 EST"
[1] "Remote data storage was already mounted."
[[1]]
[1] "540010"

[[2]]
[1] "440411"

[[3]]
[1] "440418"

[1] "Running data pull..."
[1] "540010"
[1] "running schedule..."
[1] "running physio..."
[1] "running video..."
[1] "440411"
[1] "running schedule..."
[1] "running physio..."
[1] "running video..."
[1] "440418"
[1] "running schedule..."
[1] "running physio..."
[1] "running video..."
[1] "binding schedule"
[1] "binding physio"
[1] "binding video"
[1] "Running physio calculation/aggregation..."
[1] "Saving the physio results..."
[1] "Running schedule calculation/aggregation..."
[1] "/Volumes/bierka_root/datamesh/RAW/Momentum_App/data/Subjects/540010/schedule/1641277864.324681_540010_schedule.db"
[1] "/Volumes/bierka_root/datamesh/RAW/Momentum_App/data/Subjects/440411/schedule/1641277969.061052_440411_schedule.db"
[1] "/Volumes/bierka_root/datamesh/RAW/Momentum_App/data/Subjects/440418/schedule/1641278004.271951_440418_schedule.db"
[1] "Attempting to run: 'clean_daily_recording'"
[1] "Attempting to run: 'clean_end_questionnaire'"
[1] "Attempting to run: 'clean_mood_post_task'"
[1] "Attempting to run: 'clean_mood_questionnaire'"
[1] "Attempting to run: 'clean_sleep_diary'"
[1] "Base data cleaning finished..."
[1] "Attempting to run: 'clean_daily_recording'"
[1] "Attempting to run: 'clean_end_questionnaire'"
[1] "Attempting to run: 'clean_mood_post_task'"
[1] "Attempting to run: 'clean_mood_questionnaire'"
[1] "Attempting to run: 'clean_sleep_diary'"
[1] "Base data cleaning finished..."
[1] "Attempting to run: 'clean_daily_recording'"
[1] "Attempting to run: 'clean_end_questionnaire'"
[1] "Attempting to run: 'clean_mood_post_task'"
[1] "Attempting to run: 'clean_mood_questionnaire'"
[1] "Attempting to run: 'clean_sleep_diary'"
[1] "Base data cleaning finished..."
[1] "440418 did not successfully have their schedule file processed."
<simpleError in seq.int(0, to0 - from, by): 'to' must be a finite number>
